name: Swift

on: [push]

jobs:
  test:
    runs-on: macos-11

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_12.5.app/Contents/Developer
        xcodebuild -version

    - uses: actions/checkout@v1

    - name: Launch tests
      run: |
        swift test
